### ISSUE TITLE
Weird install behavior wants files in <prefix>/include/internal/*.hpp

### ISSUE THREAD

**Issue by adamnovak** [nicolaprezza/DYNAMIC#23]
The main `dynamic.hpp` wants to include internal files as `#include <internal/whatever.hpp>`. To satisfy this when installing DYNAMIC into a prefix, we have to dump DYNAMIC's `internal` directory straight into the root of the prefix (or tell downstream projects to use `-I<prefix>/dynamic`). Either solution causes trouble if any other e.g. `internal/bwt.hpp` exists in the project's include paths.

DYNAMIC ought to reference its internal includes via a path that has the library's name in it, to prevent filename conflicts and people scratching their heads at what package is responsible for a directory like `/usr/local/include/internal`.

**Comment by nicolaprezza** [comment]
Hi Adam, you're right: the directory structure was a bit messy. It should be fixed now.
