### ISSUE TITLE
No serialization support

### ISSUE THREAD

**Issue by adamnovak** [nicolaprezza/DYNAMIC#3]
There should be support for serialization and deserialization.

**Comment by ekg** [comment]
:+1:

**Comment by nicolaprezza** [comment]
I agree, it was already in my TODO list. I'll add this feature as soon as possible.

**Comment by nicolaprezza** [comment]
Added support for serialization/deserialization with methods serialize(ostream &) and load(istream &) in all objects

**Comment by ekg** [comment]
Awesome!
